# image
FROM node:lts-alpine

# create app directory 
WORKDIR /usr/src/app

# install nodemon globally
RUN yarn add global nodemon

# copy main file to container
COPY ["package.json", "package-lock.json*", "./"]
# install all dependencies
RUN yarn

# copy in the source code
COPY . .

# expose port
EXPOSE 5000

# don't use root user
USER node

CMD ["npm", "run", "dev"]
